package main

import (
	"github.com/Godyu97/htmlkeywords/keywords"
	"log"
)

var ProjectCodeKeys = []string{
	"项目编号",
	"招标项目编号",
	"采购项目编号",
	"采购项目编码",
	"项目标号",
	"采购单编号",
	"询价书编码",
	"询价单号",
	"询价单编号",
	"标段/包编号",
	"标段（包）编号",
	"标的编号",
	"招标编号",
	"项目代码",
	"交易编号",
	"公告编号",
	"反拍单号",
	"工程编号",
	"宗地编号",
	"标段标号",
	"比选编号",
	"招标编号及包号",
	"采购编号",
	"e采项目编号",
	"招募编号",
	"合同编号",
	"标段编号",
	"序列号",
	"场次号",
	"投资项目代码",
	"编号",
}

func main() {
	ext := keywords.NewExtractor(
		ProjectCodeKeys,
		keywords.WithFilter(
			func(s string) string {
				s = keywords.DefaultFilter(s)
				return s
			}),
		keywords.WithFilter(keywords.DefaultFilter),
	)

	err := ext.ExtractKeywordsFromHtml(`<div>
							<p>

<span>
		<p>
			<strong>
				<span>
					<span>第五工程公司</span>
				</span>
			</strong>
		</p>
		<p>
			<strong>
				<span>
					<span>潮州华瀛液化天然气接收站项目</span>
				</span>
			</strong>
		</p>
		<p>
			<strong>
				<span>
					<span>十四化建五公司-潮州华瀛液化天然气接收站项目-路沿石采购方案询价采购公告</span>
				</span>
			</strong>
		</p>
	     <h2>
			 <strong>
				 <span>
					 1. 采购条件
				 </span>
			 </strong>
		</h2>
		<p>
					第五工程公司
					潮州华瀛液化天然气接收站项目项目，
				建设资金已落实，项目所需<span>十四化建五公司-潮州华瀛液化天然气接收站项目-路沿石采购方案</span>已具备询比价采购条件(采购编号:<span>A6HXCGFA231018002</span>)。采购人为<span>第五工程公司</span>
			，现进行公开询比价采购。
		</p>
		<h2>
			<strong>
				<span>
            		<span>2. 项目概况与采购内容</span>
				</span>
			</strong>
		</h2>
		<p>
			<span>
				<span>2.1</span>
			<span>
				<span>项目概况与采购内容</span>
			</span>
		</span></p>
 <p><span>(1).标段(包)编号：</span><span>A6HXCGFA231018002/01</span><span></span></p>
<p><span>标段(包)名称：</span><span>十四化建五公司-潮州华瀛液化天然气接收站项目-路沿石采购方案</span></p>
<p><span>采购内容及范围：</span><span>路沿石</span></p>
		<p>
			<span>
				<span>2.2</span>
			</span>
			<span>
			<span>
			     交货期：
			     以甲方要求为准
			</span>
			</span>
		</p>
		<p>
			<span>
				<span>2.3</span>
			</span>
			<span>
			<span>
				交货地点：
			广东省潮州市饶平县所城镇水龟地大埕湾作业区东片区潮州华瀛液化天然气接收站项目现场
			</span>
			</span>
		</p>
		<p>
			<span>
				<span>2.4</span>
			</span>
			<span>
			</span>货物质量标准或主要技术性能指标：
			</p></span>
		</p>
		<p>
			询价文件，国家及行业相关标准。
			
		</p>
		<span>
		<p>
			<span>
				<span>2.5</span>
			</span>
			<span>
				<span>其他:</span>
			</span>
		</p>
		<p>
		        无
		</p>
		</span>
		<span>
		<h2>
			<strong>
				<span>
					<span>3. 申请人资格要求</span>
				</span>
			</strong>
		</h2>
		<p>
				<span>
				  <span>3.1</span>
			   </span>
				<span>申请人资格要求</span>
		</p>
		<p>
			<span>
		     	化学云采网合格供应商
			</span>
		</p>
		<p>
			<span>
				<span>3.2</span>
			</span>
			<span>申请人不得存在下列情形之一</span>
		</p>
		<p>
			<span>
				<span>（1）与本项目其他申请人的单位负责人为同一人。</span>
		</span></p>
		<p>
			<span>
				<span>（2）与本项目其他申请人存在直接控股关系。</span>
			</span>
		</p>
		<p>
			<span>
				<span>（3）与本项目其他申请人存在管理关系。</span>
			</span>
		</p>
		<p>
			<span>
				<span>（4）近三年内在经营活动中存在以下严重不良情形：</span>
			</span>
		</p>
		<p>
			<span>
				<span>①被本项目所在地省级以上行业主管部门依法暂停、取消投标或禁止参加采购活动的。</span>
			</span>
		</p>
		<p>
			<span>
				<span>②处于被责令停产停业、暂扣或者吊销执照、暂扣、或者吊销许可证、吊销资质证书状态。</span>
			</span>
		</p>
		<p>
			<span>
				<span>③进入清算程序，或被宣告破产，或其他丧失履约能力情形的。</span>
			</span>
		</p>
		<p>
			<span>
				<span>④根据公司管理要求，被禁止参与采购活动且处于有效期内的。</span>
			</span>
		</p>
		<p>
			<span>
				<span>3.3</span>
			</span>
			<span>本次项目是否接收联合体：</span>
			<span>接受</span>
			<span>不接受</span>
			
		</p>
			<span>
		<p>
			<span>
				<span>联合体各方按照其分工协议，应当满足本条第3.1款规定的相应条件和要求；联合体各方均不得存在本条第3.2款规定的情形；联合体各方不得以自己的名义单独提交响应文件，或参加其他联合体参与本项目采购活动。否则，相关响应文件均无效。</span>
			</span>
			<span>
			</span>
		</p>
			</span>

		<h2>
			<strong>
				<span>4. 注册、登录</span>
			</strong>
		</h2>
<p>
			<span>
				<span>化学云采网|电子招标投标交易平台提供申请人注册、购买询价采购文件、下载询价采购文件、递交响应文件、澄清说明和补正等功能。</span>
			</span>
</p>
<p>
	<span>
		<span>申请人须访问化学云采网|电子招标投标交易平台标投标交易平台完成注册、交费、下载等有关操作，平台登录地址：http://bid.cncecyc.com。</span>
	</span>
</p>
		<h2>
			<strong>
				<span>5. 采购报名</span>
			</strong>
		</h2>
		<p>
				<span>
					<span>是否需要招标报名：</span>
					<span>否</span>
					<span>是</span>
				</span>
		</p>
	     <span>
			<p>
			<span>
				<span>5.1</span>
			</span>
				<span>
					<span>报名时间:</span>
				</span>
			</p>
            <p>
				<span>
					从2023-11-13 09:00		<span>起至</span>
2023-11-16 16:00止<span>(北京时间)</span>
				</span>
			</p>
            <p>
			<span>
				<span>5.2</span>
			</span>
				<span>
					<span>报名方式：</span>
				</span>
			</p>
            <p>
				<span>
					<span>注册通过后，潜在申请人请在报名规定时间内登录化学云采网|电子招标投标交易平台点击【在线报名】,上传（3.1）申请人资格要求规定的资料，点击【提交】，等待申请通过。</span>
				</span>
			</p>
		</span>
		<h2>
			<strong>
				<span>6. 询价采购文件的获取</span>
			</strong>
		</h2>
		<p>
			<span>6.1</span>
			<span>
				<span>获取时间</span>
			</span>

		</p>
		<p>
			<span>
			    从2023-11-13 09:00		<span>起至</span>
2023-11-16 16:00止
				<span>（北京时间）</span>
			</span>
		</p>
		<p>
			<span>
				<span>6.2</span>
			</span>
			<span>
				<span>购标</span>

			</span>
		</p>
		<span>
			<p>
				<span>是否需要购标：</span>
				<span>否</span>
			</p>
		</span>
		<span>
			<p>
				<span>是否需要购标：是</span>
			</p>
			<p>
				<span>售价信息：0</span>
			</p>
			</span>
		<p>
			<span>
				<span>6.3</span>
			</span>
			<span>
				<span>获取方式：</span>
			</span>
		</p>
		   <span>
			<p>
				<span>在化学云采网|电子招标投标交易平台购买询价采购文件，购买路径：【投标管理】-【购买文件】。</span>
			</p>
           </span>
              <span>
			<p>
				<span>在化学云采网|电子招标投标交易平台下载询价采购文件，下载路径：【投标管理】-【文件下载】。</span>
			</p>
			 </span>
	<h2>
			<strong>
				<span>7. 响应保证金</span>
			</strong>
		</h2>
		<p>
					<span>
						<span>是否需要响应保证金:</span><span>否</span>
					</span>
		</p>
		<h2>
			<strong>
				<span>8. 响应文件的递交</span>
			</strong>
		</h2>
		<p>
			<span>
				<span>8.1</span>
			</span>
			<span>
				<span>递交响应文件截止时间</span>
			</span>
		</p>
		<p>
			<span>
				2023-11-16 16:00<span>(北京时间)</span>
			</span>
		</p>
		<p>
			<span>
				<span>8.2</span>
			</span>
			<span>
				<span>递交方式：</span>
			</span>
		</p>
		<p>
			<span>
				<span>是否线上提交：是</span>
			</span>
		</p>
  <span>
			<p>
			<span>
				<span>申请人需下载询价采购文件制作客户端（下载地址：【门户】-【帮助中心】—【相关下载】）进行电子投标文件编制。</span>
			</span>
		    </p>
			<p>
				<span>
					<span>递交路径：【我的项目】-【操作】-【递交投标文件/网上报价】。</span>
				</span>
			</p>
	      </span>
	<span>
			<p>
				<span>
					<span>指派专人线下送至</span>#输入地点#
				</span>
			</p>
      </span>
		<p>
			<span>
				<span>8.3</span>
			</span>
			<span>
				<span>CA证书</span>
			</span>
		</p>
		<p>
			<span>
				<span>是否需要CA证书：</span>
				<span>否</span>
				<span>是</span>
			</span>
		</p>
	     <span>
			<p>
				<span>
					<span>（1）CA证书用途说明：制作标书时进行签章与加密、开标时进行解密，确保采购过程响应文件的合法性和保密性。</span>
				</span>
			</p>
            <p>
				<span>
					<span>（2）CA证书办理指南：申请人可在化学云采网|电子招标投标交易平台，点击【CA办理】进行在线申请，以及查看CA证书使用教程。</span>
				</span>
			</p>
            <p>
				<span>
					<span>（3）CA证书办理周期：一般需要2~4工作日（含邮寄时间），请申请人合理安排办理时间，避免错过投标。</span>
				</span>
			</p>
            <p>
				<span>
					<span>（4）CA证书使用须知：请在制作响应文件前提前检查CA证书有效期，如CA证书已过期，请提前进行证书更新，切勿在制作标书、上传标书、开标解密期间进行CA证书更新，以免造成无法参与投标开标的情况。</span>
				</span>
			</p>
	</span>
		<p>
			<span>
				<span>8.4</span>
			</span>
			<span>
				<span>注意事项</span>
			</span>
		</p>
	   <span>
			<p>
				<span>
					<span>（1）逾期递交的投标文件，采购人将予以拒收。</span>
				</span>
			</p>
		</span>
	 <span>
			<p>
				<span>
					<span>（1） 申请人请于响应文件递交截止时间前登录化学云采网|电子招标投标交易平台进入响应文件递交页面。</span>
				</span>
			</p>
            <p>
				<span>
					<span>（2）电子投标文件逾期上传或上传未成功，采购人拒收响应文件（平台自动关闭上传端口）。</span>
				</span>
			</p>
            <p>
				<span>
					<span>（3）采购人温馨提醒，为避免近响应文件递交截止时间网络拥堵，建议申请人适当提前上传时间。</span>
				</span>
			</p>
            <p>
				<span>
					<span>（4）届时请申请人法定代表人或其委托代理人密切关注中国化学电子招标投标交易平台。上述安排如有变化，采购人将通过发布公告的媒介发布通知。</span>
				</span>
			</p>
		 </span>
		<h2>
			<strong>
				<span>9. 询价采购文件澄清与答疑</span>
			</strong>
		</h2>
		<p>
			<span>
				<span>9.1</span>
			</span>
			<span>
				<span>申请人提问截止时间</span>
			</span>
		</p>
		<p>
			<span>
				2023-11-16 16:00
				<span>（北京时间）</span>
			</span>

		</p>
		<p>
			<span>
				<span>9.2</span>
			</span>
			<span>
				<span>提问与澄清方式</span>
			</span>
		</p>
		<p>
			<span>
				<span>提问与澄清均通过化学云采网|电子招标投标交易平台在线进行，申请人可进入【投标管理】-【我的项目】-【操作】-【采购文件澄清管理】进行提问与澄清文件的查看。</span>
			</span>
		</p>
		<span>
		<h2>
			<strong>
				<span>
					<span>10. </span>
				</span>
			</strong>
			<strong>
				<span>
					<span>发布公告的媒介</span>
				</span>
			</strong>
		</h2>
		<p>
			<span>
				<span>本项目采购公告在化学云采网|电子招标投标交易平台http://bid.cncecyc.com上发布。</span>
			</span>
		</p>
		<span>
		<p>
			<span>
			      <span>本项目采购公告同时在无</span>上发布</span>
			
			</p></span>
		
		</span>
		<span>
		<h2>
			<strong>
				<span>
						<span>11. </span>
				</span>
			</strong>
			<strong>
				<span>
					<span>其他</span>
				</span>
			</strong>
		</h2>
		<p>
			<span>
				无
			</span>
		</p>
		</span>
		<h2>
			<strong>
				<span>
				      <span>12. </span>
				</span>
			</strong>
			<strong>
				<span>
					<span>联系方式:</span>
				</span>
			</strong>
		</h2>
<ul>
<li>
<div>
<span>采</span><span>购</span><span>人：</span>
</div>
<div>第五工程公司</div>
</li>
<li>
<div>
<span>地</span><span>址：</span>
</div>
<div>广东省潮州市饶平县所城镇水龟地大埕湾作业区东片区</div>
</li>
	<li>
<div>
<span>邮</span><span>编：</span>
</div>
<div>/</div>
</li>
<li>
<div>
<span>联</span><span>系</span><span>人：</span>
</div>
<div>曾令波</div>
</li>
<li>
<div>
<span>电</span><span>话：</span>
</div>
<div>15927308660</div>
</li>
<li>
<div>
<span>邮</span><span>箱：</span>
</div>
<div>3127573730@qq.com</div>
</li>

</ul>		<p>
			<span>
				<span>第五工程公司</span>
			</span>
		</p>
<p>			<span>
<span>2023-11-14</span>			</span>
		</p>

						</span>
</div>
									
`)
	if err == nil {
		log.Println(ext.GetContent())
		log.Println(ext.GetResult(true))
		log.Println(ext.GetItemsByWeight())
	}

}
